<?php

/**
 * Live scraping registry — one Valon Worker per platform, per country + category.
 * Add a row here to enable real HTML scraping (no mock) for that store.
 *
 * adapter: cscart | woocommerce | generic | automotive | gy_digital
 */
return [

    'cache_ttl_seconds' => (int) env('LIVE_PLATFORM_CACHE_TTL', 600),

    /** When true, DE/CH/NL automotive mock listings back live scrapers when sites block bots. */
    'automotive_demo_fallback' => (bool) env('LIVE_AUTOMOTIVE_DEMO_FALLBACK', true),

    /** Multi-page automotive scraping (AutoScout24, Kleinanzeigen). */
    'automotive_max_pages' => (int) env('AUTOMOTIVE_MAX_PAGES', 10),

    'automotive_max_listings_per_platform' => (int) env('AUTOMOTIVE_MAX_LISTINGS', 100),

    'timeout_seconds' => (int) env('LIVE_PLATFORM_TIMEOUT', 60),

    'max_workers_cap' => (int) env('LIVE_PLATFORM_MAX_WORKERS', 24),

    /**
     * Universal connector — SerpAPI Google Shopping + eBay for any country (bridge layer).
     */
    'universal_bridge' => [
        'enabled' => (bool) env('UNIVERSAL_BRIDGE_ENABLED', true),
        'providers' => ['google_shopping', 'google_flights', 'ebay'],
        'always_with_local' => true,
        'when_no_local' => true,
    ],

    /**
     * Unified local-search policy — same rules for every country + category.
     * When a query targets a country with registered local platforms, global connectors are skipped.
     */
    'local_search' => [
        'exclude_global' => ['amazon', 'etsy', 'facebook_marketplace'],
        'allow_ebay_categories' => ['DE:automotive'],
        'by_country' => [
            'CH' => [
                'exclude_global' => ['ebay', 'google_shopping', 'amazon', 'etsy'],
            ],
            'DE' => [
                'exclude_global' => ['google_shopping'],
            ],
            'NL' => [
                'exclude_global' => ['ebay', 'google_shopping', 'mobile_de', 'autoscout24'],
            ],
        ],
    ],

    'platforms' => [

        // ── Kosovo · Fashion ─────────────────────────────────────────────
        'melodiapx' => [
            'adapter' => 'cscart',
            'label' => 'Melodia Px',
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor', 'marketplace'],
            'base_url' => 'https://www.melodiapx.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 3,
            'paths' => [
                'footwear' => '/atlete/',
                'men' => '/meshkuj/',
                'women' => '/femra/',
                'default' => '/meshkuj/',
            ],
            'brand_hashes' => [
                'nike' => '8-689',
                'puma' => '8-2557',
                'adidas' => '8-519',
                'reebok' => '8-767',
                'new_balance' => '8-488',
                'under_armour' => '8-1879',
                'timberland' => '8-176843',
            ],
            'items_per_page' => 32,
        ],

        'driloni' => [
            'adapter' => 'woocommerce',
            'label' => 'Driloni Sportswear',
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor', 'marketplace'],
            'base_url' => 'https://driloni-ks.com',
            'location' => 'Ferizaj, Kosovo',
            'currency' => 'EUR',
            'priority' => 4,
            'search_template' => '/?s={query}&post_type=product',
            'category_search_template' => '?s={query}&post_type=product&dgwt_wcas=1&filter=1',
            'paths' => [
                'accessories' => '/product-category/lloji-i-produktit/kapela',
            ],
            'default_query' => 'atlete',
        ],

        'albi_online' => [
            'adapter' => 'generic',
            'label' => 'Albi Online',
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor', 'marketplace'],
            'base_url' => 'https://albionline.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/?s={query}',
        ],

        'butiku_regina' => [
            'adapter' => 'generic',
            'label' => 'Butiku Regina',
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.butikuregina.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 6,
            'search_template' => '/?s={query}',
        ],

        'vedude_fashion' => [
            'adapter' => 'generic',
            'label' => 'Vedude Fashion',
            'country' => 'XK',
            'categories' => ['fashion'],
            'base_url' => 'https://vedudefashion.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 7,
            'search_template' => '/?s={query}',
        ],

        'arjana_shop' => [
            'adapter' => 'generic',
            'label' => 'Arjana Shop',
            'country' => 'XK',
            'categories' => ['fashion'],
            'base_url' => 'https://arjanashop.com',
            'location' => 'Gjakovë, Kosovo',
            'currency' => 'EUR',
            'priority' => 8,
            'search_template' => '/?s={query}',
        ],

        'ssprint_fashion' => [
            'adapter' => 'generic',
            'label' => "S'Sprint Fashion",
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://ssprintfashion.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 9,
            'search_template' => '/?s={query}',
        ],

        'am_fashion' => [
            'adapter' => 'generic',
            'label' => 'A&M Fashion',
            'country' => 'XK',
            'categories' => ['fashion'],
            'base_url' => 'https://amfashion-ks.com',
            'location' => 'Ferizaj, Kosovo',
            'currency' => 'EUR',
            'priority' => 10,
            'search_template' => '/?s={query}',
        ],

        'waikiki_kosovo' => [
            'adapter' => 'generic',
            'label' => 'Waikiki Kosovo',
            'country' => 'XK',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.lcwaikiki.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 11,
            'search_template' => '/en-XK/search?q={query}',
        ],

        'minimax_fashion' => [
            'adapter' => 'generic',
            'label' => 'Minimax Fashion',
            'country' => 'XK',
            'categories' => ['fashion', 'marketplace'],
            'base_url' => 'https://www.minimax-ks.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 12,
            'search_template' => '/?s={query}',
        ],

        // ── Kosovo · Toys & children's products ──────────────────────────
        'jumbo_ks' => [
            'adapter' => 'gy_digital',
            'label' => 'Lodra Jumbo',
            'country' => 'XK',
            'categories' => ['gaming_entertainment'],
            'toy_retailer' => true,
            'base_url' => 'https://www.jumbo-ks.com',
            'locale' => 'sq',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 1,
            'search_api_template' => '/{locale}/products/autocomplete.json?query={query}&thumbor_options[fit_in]=false&thumbor_options[height]=480&thumbor_options[width]=480',
            'default_query' => 'lodra',
        ],

        'mytoys_ks' => [
            'adapter' => 'woocommerce',
            'label' => 'My Toys',
            'country' => 'XK',
            'categories' => ['gaming_entertainment'],
            'toy_retailer' => true,
            'base_url' => 'https://mytoys-ks.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 2,
            'search_template' => '/?s={query}&post_type=product',
            'fallback_paths' => [
                '/product-category/lodra-per-djem/',
                '/product-category/lodra-per-vajza/',
                '/product-category/lodra-te-butha/',
            ],
            'default_query' => 'lodra',
        ],

        'thetoyshop_ks' => [
            'adapter' => 'woocommerce',
            'label' => 'The Entertainer Kosovo',
            'country' => 'XK',
            'categories' => ['gaming_entertainment'],
            'toy_retailer' => true,
            'base_url' => 'https://thetoyshop-ks.com',
            'location' => 'Prishtinë, Kosovo',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/?s={query}&post_type=product',
            'default_query' => 'lodra',
        ],

        // ── Kosovo · Automotive (autosallone & listings) ─────────────────
        'merrjep_auto' => [
            'adapter' => 'automotive',
            'scraper' => 'merrjep_auto',
            'label' => 'MerrJep Auto',
            'country' => 'XK',
            'categories' => ['automotive'],
            'automotive_live' => true,
            'base_url' => 'https://www.merrjep.com',
            'location' => 'Kosovo',
            'currency' => 'EUR',
            'locale' => 'sq-AL',
            'priority' => 1,
            'search_template' => '/shpallje/makina/vetura/{make}/{model}?Private=False',
        ],

        'veturaneshitje' => [
            'adapter' => 'automotive',
            'scraper' => 'veturaneshitje',
            'label' => 'Veturaneshitje.com',
            'country' => 'XK',
            'categories' => ['automotive'],
            'automotive_live' => true,
            'base_url' => 'https://www.veturaneshitje.com',
            'location' => 'Kosovo',
            'currency' => 'EUR',
            'locale' => 'sq-AL',
            'priority' => 2,
            'search_template' => '/vetura?make={make_id}',
            'make_ids' => [
                'audi' => 10,
                'bmw' => 11,
                'mercedes' => 12,
                'mercedes-benz' => 12,
                'volkswagen' => 13,
                'vw' => 13,
                'ford' => 14,
                'opel' => 15,
                'toyota' => 16,
                'honda' => 17,
                'porsche' => 18,
                'skoda' => 19,
                'seat' => 20,
            ],
        ],

        // ── Germany · Fashion ────────────────────────────────────────────
        'aboutyou_de' => [
            'adapter' => 'generic',
            'label' => 'ABOUT YOU',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.aboutyou.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/search?term={query}',
            'locale' => 'de-DE',
        ],

        'zalando_de' => [
            'adapter' => 'generic',
            'label' => 'Zalando DE',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.zalando.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 4,
            'search_template' => '/catalog/?q={query}',
            'locale' => 'de-DE',
        ],

        'otto_de' => [
            'adapter' => 'generic',
            'label' => 'OTTO',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor', 'marketplace'],
            'base_url' => 'https://www.otto.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 6,
            'search_template' => '/suche/{query}/',
            'locale' => 'de-DE',
        ],

        'bonprix_de' => [
            'adapter' => 'generic',
            'label' => 'bonprix',
            'country' => 'DE',
            'categories' => ['fashion'],
            'base_url' => 'https://www.bonprix.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 7,
            'search_template' => '/search/?q={query}',
            'locale' => 'de-DE',
        ],

        'hm_de' => [
            'adapter' => 'generic',
            'label' => 'H&M Germany',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www2.hm.com',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 8,
            'search_template' => '/de_de/search-results.html?q={query}',
            'locale' => 'de-DE',
        ],

        'peek_cloppenburg_de' => [
            'adapter' => 'generic',
            'label' => 'Peek & Cloppenburg',
            'country' => 'DE',
            'categories' => ['fashion'],
            'base_url' => 'https://www.peek-cloppenburg.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 9,
            'search_template' => '/de/suche/?q={query}',
            'locale' => 'de-DE',
        ],

        'asos_de' => [
            'adapter' => 'generic',
            'label' => 'ASOS',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.asos.com',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 10,
            'search_template' => '/de/search/?q={query}',
            'locale' => 'de-DE',
        ],

        'snipes_de' => [
            'adapter' => 'generic',
            'label' => 'SNIPES',
            'country' => 'DE',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.snipes.com',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 11,
            'search_template' => '/de-de/search?q={query}',
            'locale' => 'de-DE',
        ],

        // ── Switzerland · Fashion ────────────────────────────────────────
        'zalando_ch' => [
            'adapter' => 'generic',
            'label' => 'Zalando Switzerland',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.zalando.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 3,
            'search_template' => '/catalog/?q={query}',
            'locale' => 'de-CH',
        ],

        'aboutyou_ch' => [
            'adapter' => 'generic',
            'label' => 'ABOUT YOU Switzerland',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.aboutyou.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 4,
            'search_template' => '/search?term={query}',
            'locale' => 'de-CH',
        ],

        'ochsnersport_ch' => [
            'adapter' => 'generic',
            'label' => 'Ochsner Sport',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.ochsnersport.com',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 5,
            'search_template' => '/ch-de/search?q={query}',
            'locale' => 'de-CH',
        ],

        'intersport_ch' => [
            'adapter' => 'generic',
            'scraper' => 'shopify',
            'label' => 'Intersport Switzerland',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.intersport.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 6,
            'search_template' => '/search?q={query}&type=product',
            'locale' => 'de-CH',
        ],

        'sportxx_ch' => [
            'adapter' => 'generic',
            'label' => 'SportXX',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.sportxx.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 7,
            'search_template' => '/de/search?q={query}',
            'locale' => 'de-CH',
        ],

        'decathlon_ch' => [
            'adapter' => 'generic',
            'label' => 'Decathlon Switzerland',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www.decathlon.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 8,
            'search_template' => '/de/search?Ntt={query}',
            'locale' => 'de-CH',
        ],

        'hm_ch' => [
            'adapter' => 'generic',
            'label' => 'H&M Switzerland',
            'country' => 'CH',
            'categories' => ['fashion', 'sports_outdoor'],
            'base_url' => 'https://www2.hm.com',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 9,
            'search_template' => '/de_ch/search-results.html?q={query}',
            'locale' => 'de-CH',
        ],

        // ── Germany · Automotive (live HTML scraping) ────────────────────
        'autoscout24_de' => [
            'adapter' => 'automotive',
            'scraper' => 'autoscout24',
            'label' => 'AutoScout24 Germany',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autoscout24.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/lst/{make}/{model}',
            'locale' => 'de-DE',
        ],

        'kleinanzeigen' => [
            'adapter' => 'automotive',
            'scraper' => 'kleinanzeigen',
            'label' => 'Kleinanzeigen',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.kleinanzeigen.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 4,
            'search_template' => '/s-autos/{make}/k0',
            'locale' => 'de-DE',
        ],

        'mobile_de' => [
            'adapter' => 'automotive',
            'scraper' => 'mobile_de',
            'label' => 'mobile.de',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.mobile.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/fahrzeuge/search.html?isSearchRequest=true&ms={make};;&ref=quickSearch',
            'locale' => 'de-DE',
        ],

        'heycar_de' => [
            'adapter' => 'automotive',
            'scraper' => 'heycar',
            'label' => 'heycar',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.heycar.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 6,
            'search_template' => '/de/autos/{make}/{model}',
            'locale' => 'de-DE',
        ],

        'autoplenum' => [
            'adapter' => 'automotive',
            'scraper' => 'autoplenum',
            'label' => 'Autoplenum.de',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autoplenum.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 7,
            'search_template' => '/gebrauchtwagen/{make}/{model}.html',
            'locale' => 'de-DE',
        ],

        'pkw_de' => [
            'adapter' => 'automotive',
            'scraper' => 'pkw_de',
            'label' => 'PKW.de',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.pkw.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 8,
            'search_template' => '/gebrauchtwagen/suche/{make}/{model}',
            'locale' => 'de-DE',
        ],

        'wirkaufendeinauto' => [
            'adapter' => 'automotive',
            'scraper' => 'wirkaufendeinauto',
            'label' => 'wirkaufendeinauto.de',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.wirkaufendeinauto.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 9,
            'search_template' => '/gebrauchtwagen/{make}/{model}/',
            'locale' => 'de-DE',
        ],

        'facebook_marketplace_de' => [
            'adapter' => 'automotive',
            'scraper' => 'facebook_marketplace',
            'label' => 'Facebook Marketplace DE',
            'country' => 'DE',
            'categories' => ['automotive'],
            'base_url' => 'https://www.facebook.com',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 10,
            'search_template' => '/marketplace/search?query={query}',
            'locale' => 'de-DE',
        ],

        // ── Germany · Electronics (live HTML scraping) ───────────────────
        'mediamarkt' => [
            'adapter' => 'generic',
            'scraper' => 'mediamarkt',
            'label' => 'MediaMarkt',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment'],
            'base_url' => 'https://www.mediamarkt.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/de/search.html?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'saturn' => [
            'adapter' => 'generic',
            'scraper' => 'saturn',
            'label' => 'Saturn',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment'],
            'base_url' => 'https://www.saturn.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 4,
            'search_template' => '/de/search.html?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'cyberport' => [
            'adapter' => 'generic',
            'scraper' => 'cyberport',
            'label' => 'Cyberport',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.cyberport.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/search?query={query}',
            'default_query' => 'macbook',
            'locale' => 'de-DE',
        ],

        'alternate' => [
            'adapter' => 'generic',
            'scraper' => 'alternate',
            'label' => 'Alternate',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.alternate.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 6,
            'search_template' => '/html/search.html?query={query}',
            'default_query' => 'macbook',
            'locale' => 'de-DE',
        ],

        'conrad' => [
            'adapter' => 'generic',
            'label' => 'Conrad Electronic',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.conrad.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 7,
            'search_template' => '/de/search.html?search={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'notebooksbilliger' => [
            'adapter' => 'generic',
            'scraper' => 'notebooksbilliger',
            'label' => 'Notebooksbilliger',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.notebooksbilliger.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 8,
            'search_template' => '/search/{query}',
            'default_query' => 'macbook',
            'locale' => 'de-DE',
        ],

        'mindfactory' => [
            'adapter' => 'generic',
            'label' => 'Mindfactory',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.mindfactory.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 9,
            'search_template' => '/search_result.php/search_search={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'caseking' => [
            'adapter' => 'generic',
            'label' => 'Caseking',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.caseking.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 10,
            'search_template' => '/search?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'computeruniverse' => [
            'adapter' => 'generic',
            'label' => 'Computeruniverse',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.computeruniverse.net',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 11,
            'search_template' => '/de/search?q={query}',
            'default_query' => 'macbook',
            'locale' => 'de-DE',
        ],

        'reichelt' => [
            'adapter' => 'generic',
            'label' => 'Reichelt Elektronik',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.reichelt.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 12,
            'search_template' => '/index.html?ACTION=446&QUERY={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'euronics' => [
            'adapter' => 'generic',
            'label' => 'Euronics',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.euronics.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 13,
            'search_template' => '/technik/suche?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'expert_de' => [
            'adapter' => 'generic',
            'label' => 'Expert',
            'country' => 'DE',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.expert.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 14,
            'search_template' => '/suche/{query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'pearl' => [
            'adapter' => 'generic',
            'label' => 'Pearl',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.pearl.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 15,
            'search_template' => '/search?q={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'jacob' => [
            'adapter' => 'generic',
            'label' => 'Jacob Elektronik',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.jacob.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 16,
            'search_template' => '/search?q={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'voelkner' => [
            'adapter' => 'generic',
            'label' => 'Voelkner',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.voelkner.de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 17,
            'search_template' => '/search.php?search={query}',
            'default_query' => 'laptop',
            'locale' => 'de-DE',
        ],

        'apple_de' => [
            'adapter' => 'generic',
            'scraper' => 'apple_store',
            'label' => 'Apple Store Germany',
            'country' => 'DE',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.apple.com',
            'shop_prefix' => 'de',
            'location' => 'Germany',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/de/shop/search/{slug}',
            'default_query' => 'macbook',
            'locale' => 'de-DE',
        ],

        'autoscout24_ch' => [
            'adapter' => 'automotive',
            'scraper' => 'autoscout24',
            'label' => 'AutoScout24 Switzerland',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autoscout24.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 3,
            'search_template' => '/lst/{make}/{model}',
            'locale' => 'de-CH',
        ],

        'autolina' => [
            'adapter' => 'automotive',
            'scraper' => 'autolina',
            'label' => 'Autolina',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autolina.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 2,
            'search_template' => '/{make}/{model}',
            'locale' => 'de-CH',
        ],

        'autogrid_ch' => [
            'adapter' => 'automotive',
            'scraper' => 'autogrid',
            'label' => 'Autogrid Switzerland',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autogrid.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 4,
            'search_template' => '/inserate/marke/{make}-occasionen',
            'locale' => 'de-CH',
        ],

        'car_trade24' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Car Trade24',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://cartrade24.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 5,
            'search_template' => '/autos?make={make}&model={model}',
            'locale' => 'de-CH',
        ],

        'carlando' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Carlando',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://carlando.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 6,
            'search_template' => '/de/suche?q={query}',
            'locale' => 'de-CH',
        ],

        'carindex' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Carindex',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.carindex.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 7,
            'search_template' => '/?s={query}',
            'locale' => 'de-CH',
        ],

        'amag' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'AMAG',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.amag.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 8,
            'search_template' => '/de/occasionen?search={query}',
            'locale' => 'de-CH',
        ],

        'troovo' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Troovo Auto',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.troovo.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 9,
            'search_template' => '/de/autos?make={make}&model={model}',
            'locale' => 'de-CH',
        ],

        'motoauto_ch' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'MotoAuto Switzerland',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.motoauto.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 10,
            'search_template' => '/{make}/{model}',
            'locale' => 'de-CH',
        ],

        'ricardo' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Ricardo.ch',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.ricardo.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 11,
            'search_template' => '/de/s/autos/{slug}',
            'locale' => 'de-CH',
        ],

        'tutti' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Tutti.ch',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.tutti.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 12,
            'search_template' => '/de/q/auto/{slug}',
            'locale' => 'de-CH',
        ],

        'facebook_marketplace' => [
            'adapter' => 'automotive',
            'scraper' => 'swiss_html',
            'label' => 'Facebook Marketplace',
            'country' => 'CH',
            'categories' => ['automotive'],
            'base_url' => 'https://www.facebook.com',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 13,
            'search_template' => '/marketplace/search/?query={query}',
            'locale' => 'de-CH',
        ],

        // ── Switzerland · Electronics ────────────────────────────────────
        'digitec_ch' => [
            'adapter' => 'generic',
            'scraper' => 'digitec',
            'label' => 'Digitec',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'gaming_entertainment', 'home_appliances'],
            'base_url' => 'https://www.digitec.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 2,
            'search_template' => '/de/search?q={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'galaxus_ch' => [
            'adapter' => 'generic',
            'scraper' => 'galaxus',
            'label' => 'Galaxus',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'gaming_entertainment', 'home_appliances', 'marketplace', 'fashion', 'sports_outdoor'],
            'base_url' => 'https://www.galaxus.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 3,
            'search_template' => '/de/search?q={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'manor_ch' => [
            'adapter' => 'generic',
            'scraper' => 'manor',
            'label' => 'Manor',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'home_appliances', 'marketplace', 'fashion', 'sports_outdoor'],
            'base_url' => 'https://www.manor.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 4,
            'search_template' => '/de/search?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'apple_ch' => [
            'adapter' => 'generic',
            'scraper' => 'apple_store',
            'label' => 'Apple Store Switzerland',
            'country' => 'CH',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.apple.com',
            'shop_prefix' => 'ch-de',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 5,
            'search_template' => '/ch-de/shop/search/{slug}',
            'default_query' => 'macbook',
            'locale' => 'de-CH',
        ],

        'interdiscount_ch' => [
            'adapter' => 'generic',
            'label' => 'Interdiscount',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.interdiscount.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 6,
            'search_template' => '/de/search?q={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'mediamarkt_ch' => [
            'adapter' => 'generic',
            'label' => 'MediaMarkt Switzerland',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment'],
            'base_url' => 'https://www.mediamarkt.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 7,
            'search_template' => '/de/search.html?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'steg_ch' => [
            'adapter' => 'generic',
            'label' => 'Steg Electronics',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.steg-electronics.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 8,
            'search_template' => '/de/search?sSearch={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'fust_ch' => [
            'adapter' => 'generic',
            'label' => 'Fust',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.fust.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 9,
            'search_template' => '/de/search?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'brack_ch' => [
            'adapter' => 'generic',
            'label' => 'Brack.ch',
            'country' => 'CH',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.brack.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 10,
            'search_template' => '/de/s?query={query}',
            'default_query' => 'laptop',
            'locale' => 'de-CH',
        ],

        'autoscout24_nl' => [
            'adapter' => 'automotive',
            'scraper' => 'autoscout24',
            'label' => 'AutoScout24 Netherlands',
            'country' => 'NL',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autoscout24.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/lst/{make}/{model}',
            'locale' => 'nl-NL',
        ],

        // ── United States · Automotive ───────────────────────────────────
        'cars_com_us' => [
            'adapter' => 'generic',
            'label' => 'Cars.com',
            'country' => 'US',
            'categories' => ['automotive'],
            'base_url' => 'https://www.cars.com',
            'location' => 'New York, United States',
            'currency' => 'USD',
            'priority' => 3,
            'search_template' => '/shopping/results/?keyword={query}&zip={zip}&maximum_distance=50',
            'default_zip' => '10001',
            'default_query' => 'used cars',
            'locale' => 'en-US',
        ],

        'autotrader_us' => [
            'adapter' => 'generic',
            'label' => 'Autotrader',
            'country' => 'US',
            'categories' => ['automotive'],
            'base_url' => 'https://www.autotrader.com',
            'location' => 'New York, United States',
            'currency' => 'USD',
            'priority' => 4,
            'search_template' => '/cars-for-sale/all-cars?searchByKeywords={query}&zip={zip}',
            'default_zip' => '10001',
            'default_query' => 'car',
            'locale' => 'en-US',
        ],

        'cargurus_us' => [
            'adapter' => 'generic',
            'label' => 'CarGurus',
            'country' => 'US',
            'categories' => ['automotive'],
            'base_url' => 'https://www.cargurus.com',
            'location' => 'New York, United States',
            'currency' => 'USD',
            'priority' => 5,
            'search_template' => '/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?zip={zip}&search={query}',
            'default_zip' => '10001',
            'default_query' => 'used car',
            'locale' => 'en-US',
        ],

        'carfax_us' => [
            'adapter' => 'generic',
            'label' => 'CARFAX',
            'country' => 'US',
            'categories' => ['automotive'],
            'base_url' => 'https://www.carfax.com',
            'location' => 'New York, United States',
            'currency' => 'USD',
            'priority' => 6,
            'search_template' => '/Cars-for-Sale?zip={zip}&keyword={query}',
            'default_zip' => '10001',
            'default_query' => 'car',
            'locale' => 'en-US',
        ],

        'facebook_marketplace_us' => [
            'adapter' => 'generic',
            'label' => 'Facebook Marketplace US',
            'country' => 'US',
            'categories' => ['automotive', 'electronics_tech', 'real_estate', 'marketplace'],
            'base_url' => 'https://www.facebook.com',
            'location' => 'New York, United States',
            'currency' => 'USD',
            'priority' => 7,
            'search_template' => '/marketplace/search/?query={query}',
            'default_query' => 'car',
            'locale' => 'en-US',
        ],

        // ── Netherlands · Electronics ────────────────────────────────────
        'coolblue_nl' => [
            'adapter' => 'generic',
            'label' => 'Coolblue',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment'],
            'base_url' => 'https://www.coolblue.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/zoeken?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'bol_com_nl' => [
            'adapter' => 'generic',
            'label' => 'bol.com',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'gaming_entertainment', 'marketplace'],
            'base_url' => 'https://www.bol.com',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 4,
            'search_template' => '/nl/nl/s/?searchtext={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'mediamarkt_nl' => [
            'adapter' => 'generic',
            'label' => 'MediaMarkt NL',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment'],
            'base_url' => 'https://www.mediamarkt.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 5,
            'search_template' => '/nl/search.html?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'bcc_nl' => [
            'adapter' => 'generic',
            'label' => 'BCC',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'home_appliances'],
            'base_url' => 'https://www.bcc.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 6,
            'search_template' => '/zoeken?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'alternate_nl' => [
            'adapter' => 'generic',
            'label' => 'Alternate.nl',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.alternate.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 7,
            'search_template' => '/zoeken?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'azerty_nl' => [
            'adapter' => 'generic',
            'label' => 'Azerty',
            'country' => 'NL',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.azerty.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 8,
            'search_template' => '/zoeken/{query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'paradigit_nl' => [
            'adapter' => 'generic',
            'label' => 'Paradigit',
            'country' => 'NL',
            'categories' => ['electronics_tech', 'gaming_entertainment'],
            'base_url' => 'https://www.paradigit.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 9,
            'search_template' => '/zoeken?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        'centralpoint_nl' => [
            'adapter' => 'generic',
            'label' => 'Centralpoint',
            'country' => 'NL',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.centralpoint.nl',
            'location' => 'Netherlands',
            'currency' => 'EUR',
            'priority' => 10,
            'search_template' => '/nl/search?query={query}',
            'default_query' => 'laptop',
            'locale' => 'nl-NL',
        ],

        // ── United States · Electronics ──────────────────────────────────
        'bestbuy_us' => [
            'adapter' => 'generic',
            'label' => 'Best Buy',
            'country' => 'US',
            'categories' => ['electronics_tech', 'gaming_entertainment', 'home_appliances'],
            'base_url' => 'https://www.bestbuy.com',
            'location' => 'United States',
            'currency' => 'USD',
            'priority' => 3,
            'search_template' => '/site/searchpage.jsp?st={query}',
            'default_query' => 'iphone',
            'default_zip' => '20001',
            'locale' => 'en-US',
        ],

        'apple_us' => [
            'adapter' => 'generic',
            'label' => 'Apple Store US',
            'country' => 'US',
            'categories' => ['electronics_tech'],
            'base_url' => 'https://www.apple.com',
            'location' => 'United States',
            'currency' => 'USD',
            'priority' => 4,
            'search_template' => '/us/search/{query}',
            'default_query' => 'iphone',
            'locale' => 'en-US',
        ],

        'target_us' => [
            'adapter' => 'generic',
            'label' => 'Target',
            'country' => 'US',
            'categories' => ['electronics_tech', 'home_appliances', 'marketplace'],
            'base_url' => 'https://www.target.com',
            'location' => 'United States',
            'currency' => 'USD',
            'priority' => 5,
            'search_template' => '/s?searchTerm={query}',
            'default_query' => 'iphone',
            'locale' => 'en-US',
        ],

        'walmart_us' => [
            'adapter' => 'generic',
            'label' => 'Walmart',
            'country' => 'US',
            'categories' => ['electronics_tech', 'home_appliances', 'marketplace'],
            'base_url' => 'https://www.walmart.com',
            'location' => 'United States',
            'currency' => 'USD',
            'priority' => 6,
            'search_template' => '/search?q={query}',
            'default_query' => 'iphone',
            'locale' => 'en-US',
        ],

        'amazon_us' => [
            'adapter' => 'generic',
            'label' => 'Amazon US',
            'country' => 'US',
            'categories' => ['electronics_tech', 'home_appliances', 'gaming_entertainment', 'marketplace'],
            'base_url' => 'https://www.amazon.com',
            'location' => 'United States',
            'currency' => 'USD',
            'priority' => 7,
            'search_template' => '/s?k={query}',
            'default_query' => 'iphone',
            'locale' => 'en-US',
        ],

        // ── Switzerland · Real Estate ────────────────────────────────────
        'homegate_ch' => [
            'adapter' => 'real_estate',
            'label' => 'Homegate',
            'country' => 'CH',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.homegate.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 3,
            'search_template' => '/kaufen/wohnung/ort-{query}/trefferliste',
            'default_query' => 'schweiz',
            'locale' => 'de-CH',
        ],

        'immoscout24_ch' => [
            'adapter' => 'real_estate',
            'label' => 'ImmoScout24 Switzerland',
            'country' => 'CH',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.immoscout24.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 4,
            'search_template' => '/kaufen/wohnung',
            'default_query' => 'wohnung',
            'locale' => 'de-CH',
        ],

        'newhome_ch' => [
            'adapter' => 'real_estate',
            'label' => 'newhome.ch',
            'country' => 'CH',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.newhome.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 5,
            'search_template' => '/kaufen/suche?location={query}',
            'default_query' => 'schweiz',
            'locale' => 'de-CH',
        ],

        'comparis_immobilien' => [
            'adapter' => 'real_estate',
            'label' => 'Comparis Immobilien',
            'country' => 'CH',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.comparis.ch',
            'location' => 'Switzerland',
            'currency' => 'CHF',
            'priority' => 6,
            'search_template' => '/immobilien/marktplatz/wohnung-kaufen?q={query}',
            'default_query' => 'wohnung',
            'locale' => 'de-CH',
        ],

        // ── United Kingdom · Real Estate ─────────────────────────────────
        'rightmove_uk' => [
            'adapter' => 'generic',
            'label' => 'Rightmove',
            'country' => 'GB',
            'categories' => ['real_estate'],
            'cities' => ['London'],
            'base_url' => 'https://www.rightmove.co.uk',
            'location' => 'London, United Kingdom',
            'currency' => 'GBP',
            'priority' => 3,
            'search_template' => '/property-for-sale/find.html?searchLocation={query}',
            'default_query' => 'London',
            'locale' => 'en-GB',
        ],

        'zoopla_uk' => [
            'adapter' => 'generic',
            'label' => 'Zoopla',
            'country' => 'GB',
            'categories' => ['real_estate'],
            'cities' => ['London'],
            'base_url' => 'https://www.zoopla.co.uk',
            'location' => 'London, United Kingdom',
            'currency' => 'GBP',
            'priority' => 4,
            'search_template' => '/for-sale/property/london/?q={query}',
            'default_query' => 'London',
            'locale' => 'en-GB',
        ],

        'onthemarket_uk' => [
            'adapter' => 'generic',
            'label' => 'OnTheMarket',
            'country' => 'GB',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.onthemarket.com',
            'location' => 'United Kingdom',
            'currency' => 'GBP',
            'priority' => 5,
            'search_template' => '/for-sale/property/london/?q={query}',
            'default_query' => 'London',
            'locale' => 'en-GB',
        ],

        'primelocation_uk' => [
            'adapter' => 'generic',
            'label' => 'PrimeLocation',
            'country' => 'GB',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.primelocation.com',
            'location' => 'United Kingdom',
            'currency' => 'GBP',
            'priority' => 6,
            'search_template' => '/for-sale/property/london/?q={query}',
            'default_query' => 'London',
            'locale' => 'en-GB',
        ],

        'openrent_uk' => [
            'adapter' => 'generic',
            'label' => 'OpenRent',
            'country' => 'GB',
            'categories' => ['real_estate'],
            'base_url' => 'https://www.openrent.co.uk',
            'location' => 'United Kingdom',
            'currency' => 'GBP',
            'priority' => 7,
            'search_template' => '/search?q={query}',
            'default_query' => 'London',
            'locale' => 'en-GB',
        ],

        // ── Worldwide · Universal search ───────────────────────────────
        'ebay_ww' => [
            'adapter' => 'generic',
            'label' => 'eBay Worldwide',
            'country' => 'WW',
            'global' => true,
            'categories' => ['sports_outdoor', 'electronics_tech', 'automotive', 'fashion', 'marketplace'],
            'base_url' => 'https://www.ebay.com',
            'location' => 'Worldwide',
            'currency' => 'USD',
            'priority' => 1,
            'search_template' => '/sch/i.html?_nkw={query}',
            'default_query' => 'scooter',
            'locale' => 'en-US',
        ],

        'amazon_ww' => [
            'adapter' => 'generic',
            'label' => 'Amazon Worldwide',
            'country' => 'WW',
            'global' => true,
            'categories' => ['sports_outdoor', 'electronics_tech', 'automotive', 'fashion', 'home_appliances', 'marketplace'],
            'base_url' => 'https://www.amazon.com',
            'location' => 'Worldwide',
            'currency' => 'USD',
            'priority' => 2,
            'search_template' => '/s?k={query}',
            'default_query' => 'scooter',
            'locale' => 'en-US',
        ],

        'decathlon_ww' => [
            'adapter' => 'generic',
            'label' => 'Decathlon',
            'country' => 'WW',
            'global' => true,
            'categories' => ['sports_outdoor', 'fashion'],
            'base_url' => 'https://www.decathlon.com',
            'location' => 'Worldwide',
            'currency' => 'EUR',
            'priority' => 3,
            'search_template' => '/search?query={query}',
            'default_query' => 'scooter',
            'locale' => 'en-US',
        ],

        'aliexpress_ww' => [
            'adapter' => 'generic',
            'label' => 'AliExpress',
            'country' => 'WW',
            'global' => true,
            'categories' => ['sports_outdoor', 'electronics_tech', 'fashion', 'marketplace'],
            'base_url' => 'https://www.aliexpress.com',
            'location' => 'Worldwide',
            'currency' => 'USD',
            'priority' => 4,
            'search_template' => '/wholesale?SearchText={query}',
            'default_query' => 'electric scooter',
            'locale' => 'en-US',
        ],

        'facebook_marketplace_ww' => [
            'adapter' => 'generic',
            'label' => 'Facebook Marketplace',
            'country' => 'WW',
            'global' => true,
            'categories' => ['sports_outdoor', 'automotive', 'electronics_tech', 'real_estate', 'marketplace'],
            'base_url' => 'https://www.facebook.com',
            'location' => 'Worldwide',
            'currency' => 'USD',
            'priority' => 5,
            'search_template' => '/marketplace/search/?query={query}',
            'default_query' => 'scooter',
            'locale' => 'en-US',
        ],
    ],
];
